from src.utils import load_hiking_dataset , load_df2_unidade1,load_wine_dataset, load_df1_unidade1, load_volunteer_dataset
import pandas as pd

volunteer = load_volunteer_dataset()
hiking = load_hiking_dataset()
wine  = load_wine_dataset()
df1 = load_df1_unidade1()
df2 = load_df2_unidade1()

print("Retorna as primeras n linhas")
print(hiking.head())
print("--------------------")
print("Retorna um resumo das principais características de um DataFrame")
print(hiking.info())
print("--------------------")
print("Retorna um resumo estatístico rápido de um DataFrame")
print(wine.describe())
print("--------------------")
print("Retorna a tabela 1")
print(df1)
print("--------------------")
print("Retorna a tabela removendo as linhas que tem valores faltando")
print(df1.dropna())
print("--------------------")
print("Retorna a tabela 2")
print(df2)
print("--------------------")
print("Retorna a tabela 2 removendo as linhas especificadas")
print(df2.drop([1, 2]))
print("--------------------")
print("Retorna a tabela 1 com a coluna A removida(tem que ter o axis=1 para funcionar)")
print(df1.drop("A", axis=1))
print("--------------------")
print("Retorna a soma da quantidade de valores daltando em cada coluna")
print(df1.isna().sum())
print("--------------------")
print("Retorna a tabela 1 removendo as linhas, em que na coluna B tem valores faltando")
print(df1.dropna(subset="B"))
print("--------------------")
print("Retorna a tabela 1 removendo todas as linhas que tem 2 ou mais valores faltando")
print(df1.dropna(thresh=2))
print("--------------------")
print(df2.info())
print("--------------------")
print("Antes da mudança")
print(df2.dtypes)
print("--------------------")
#modifica o dtype da coluna C para int64
df2["C"] = df2["C"].astype("int64")
print("Depois da mudança")
print(df2.dtypes)
